<?php
//Do Re Mi Fa Sol La Si Do
$scale[7] = [-1,-1,-1,-1,-1,-1,-1];
$scale[6] = [-1,-1,-1,0,-1,-1,-1];
$scale[5] = [0,-1,-1,0,-1,-1,-1];
$scale[4] = [0,-1,-1,0,0,-1,-1];
$scale[3] = [0,0,-1,0,0,-1,-1];
$scale[2] = [0,0,-1,0,0,0,-1];
$scale[1] = [0,0,0,0,0,0,-1];
$scale[0] = [0,0,0,0,0,0,0];
$scale[-1] = [0,0,0,1,0,0,0];
$scale[-2] = [1,0,0,1,0,0,0];
$scale[-3] = [1,0,0,1,1,0,0];
$scale[-4] = [1,1,0,1,1,0,0];
$scale[-5] = [1,1,0,1,1,1,0];
$scale[-6] = [1,1,1,1,1,1,0];
$scale[-7] = [1,1,1,1,1,1,1];

$notes[0] = ['octave' => 1,'note' => 'Do'];
$notes[1] = ['octave' => 1,'note' => 'Do #'];
$notes[2] = ['octave' => 1,'note' => 'Re'];
$notes[3] = ['octave' => 1,'note' => 'Re #'];
$notes[4] = ['octave' => 1,'note' => 'Mi'];
$notes[5] = ['octave' => 1,'note' => 'Fa'];
$notes[6] = ['octave' => 1,'note' => 'Fa #'];
$notes[7] = ['octave' => 1,'note' => 'Sol'];
$notes[8] = ['octave' => 1,'note' => 'Sol #'];
$notes[9] = ['octave' => 1,'note' => 'La'];
$notes[10] = ['octave' => 1,'note' => 'La #'];
$notes[11] = ['octave' => 1,'note' => 'Si'];
$notes[12] = ['octave' => 2,'note' => 'Do'];
$notes[13] = ['octave' => 2,'note' => 'Do #'];
$notes[14] = ['octave' => 2,'note' => 'Re'];
$notes[15] = ['octave' => 2,'note' => 'Re #'];
$notes[16] = ['octave' => 2,'note' => 'Mi'];
$notes[17] = ['octave' => 2,'note' => 'Fa'];
$notes[18] = ['octave' => 2,'note' => 'Fa #'];
$notes[19] = ['octave' => 2,'note' => 'Sol'];
$notes[20] = ['octave' => 2,'note' => 'Sol #'];
$notes[21] = ['octave' => 2,'note' => 'La'];
$notes[22] = ['octave' => 2,'note' => 'La #'];
$notes[23] = ['octave' => 2,'note' => 'Si'];
$notes[24] = ['octave' => 3,'note' => 'Do'];
$notes[25] = ['octave' => 3,'note' => 'Do #'];
$notes[26] = ['octave' => 3,'note' => 'Re'];
$notes[27] = ['octave' => 3,'note' => 'Re #'];
$notes[28] = ['octave' => 3,'note' => 'Mi'];
$notes[29] = ['octave' => 3,'note' => 'Fa'];
$notes[30] = ['octave' => 3,'note' => 'Fa #'];
$notes[31] = ['octave' => 3,'note' => 'Sol'];
$notes[32] = ['octave' => 3,'note' => 'Sol #'];
$notes[33] = ['octave' => 3,'note' => 'La'];
$notes[34] = ['octave' => 3,'note' => 'La #'];
$notes[35] = ['octave' => 3,'note' => 'Si'];
$notes[36] = ['octave' => 4,'note' => 'Do'];
$notes[37] = ['octave' => 4,'note' => 'Do #'];
$notes[38] = ['octave' => 4,'note' => 'Re'];
$notes[39] = ['octave' => 4,'note' => 'Re #'];
$notes[40] = ['octave' => 4,'note' => 'Mi'];
$notes[41] = ['octave' => 4,'note' => 'Fa'];
$notes[42] = ['octave' => 4,'note' => 'Fa #'];
$notes[43] = ['octave' => 4,'note' => 'Sol'];
$notes[44] = ['octave' => 4,'note' => 'Sol #'];
$notes[45] = ['octave' => 4,'note' => 'La'];
$notes[46] = ['octave' => 4,'note' => 'La #'];
$notes[47] = ['octave' => 4,'note' => 'Si'];
$notes[48] = ['octave' => 5,'note' => 'Do'];
$notes[49] = ['octave' => 5,'note' => 'Do #'];
$notes[50] = ['octave' => 5,'note' => 'Re'];
$notes[51] = ['octave' => 5,'note' => 'Re #'];
$notes[52] = ['octave' => 5,'note' => 'Mi'];
$notes[53] = ['octave' => 5,'note' => 'Fa'];
$notes[54] = ['octave' => 5,'note' => 'Fa #'];
$notes[55] = ['octave' => 5,'note' => 'Sol'];
$notes[56] = ['octave' => 5,'note' => 'Sol #'];
$notes[57] = ['octave' => 5,'note' => 'La'];
$notes[58] = ['octave' => 5,'note' => 'La #'];
$notes[59] = ['octave' => 5,'note' => 'Si'];
$notes[60] = ['octave' => 6,'note' => 'Do'];
$notes[61] = ['octave' => 6,'note' => 'Do #'];
$notes[62] = ['octave' => 6,'note' => 'Re'];
$notes[63] = ['octave' => 6,'note' => 'Re #'];
$notes[64] = ['octave' => 6,'note' => 'Mi'];
$notes[65] = ['octave' => 6,'note' => 'Fa'];
$notes[66] = ['octave' => 6,'note' => 'Fa #'];
$notes[67] = ['octave' => 6,'note' => 'Sol'];
$notes[68] = ['octave' => 6,'note' => 'Sol #'];
$notes[69] = ['octave' => 6,'note' => 'La'];
$notes[70] = ['octave' => 6,'note' => 'La #'];
$notes[71] = ['octave' => 6,'note' => 'Si'];
$notes[72] = ['octave' => 7,'note' => 'Do'];
$notes[73] = ['octave' => 7,'note' => 'Do #'];
$notes[74] = ['octave' => 7,'note' => 'Re'];
$notes[75] = ['octave' => 7,'note' => 'Re #'];
$notes[76] = ['octave' => 7,'note' => 'Mi'];
$notes[77] = ['octave' => 7,'note' => 'Fa'];
$notes[78] = ['octave' => 7,'note' => 'Fa #'];
$notes[79] = ['octave' => 7,'note' => 'Sol'];
$notes[80] = ['octave' => 7,'note' => 'Sol #'];
$notes[81] = ['octave' => 7,'note' => 'La'];
$notes[82] = ['octave' => 7,'note' => 'La #'];
$notes[83] = ['octave' => 7,'note' => 'Si'];
$notes[84] = ['octave' => 8,'note' => 'Do'];
$notes[85] = ['octave' => 8,'note' => 'Do #'];
$notes[86] = ['octave' => 8,'note' => 'Re'];
$notes[87] = ['octave' => 8,'note' => 'Re #'];
$notes[88] = ['octave' => 8,'note' => 'Mi'];
$notes[89] = ['octave' => 8,'note' => 'Fa'];
$notes[90] = ['octave' => 8,'note' => 'Fa #'];
$notes[91] = ['octave' => 8,'note' => 'Sol'];
$notes[92] = ['octave' => 8,'note' => 'Sol #'];
$notes[93] = ['octave' => 8,'note' => 'La'];
$notes[94] = ['octave' => 8,'note' => 'La #'];
$notes[95] = ['octave' => 8,'note' => 'Si'];
$notes[96] = ['octave' => 9,'note' => 'Do'];
$notes[97] = ['octave' => 9,'note' => 'Do #'];
$notes[98] = ['octave' => 9,'note' => 'Re'];
$notes[99] = ['octave' => 9,'note' => 'Re #'];
$notes[100] = ['octave' => 9,'note' => 'Mi'];
$notes[101] = ['octave' => 9,'note' => 'Fa'];
$notes[102] = ['octave' => 9,'note' => 'Fa #'];
$notes[103] = ['octave' => 9,'note' => 'Sol'];
$notes[104] = ['octave' => 9,'note' => 'Sol #'];
$notes[105] = ['octave' => 9,'note' => 'La'];
$notes[106] = ['octave' => 9,'note' => 'La #'];
$notes[107] = ['octave' => 9,'note' => 'Si'];
$notes[108] = ['octave' => 10,'note' => 'Do'];
$notes[109] = ['octave' => 10,'note' => 'Do #'];
$notes[110] = ['octave' => 10,'note' => 'Re'];
$notes[111] = ['octave' => 10,'note' => 'Re #'];
$notes[112] = ['octave' => 10,'note' => 'Mi'];
$notes[113] = ['octave' => 10,'note' => 'Fa'];
$notes[114] = ['octave' => 10,'note' => 'Fa #'];
$notes[115] = ['octave' => 10,'note' => 'Sol'];
$notes[116] = ['octave' => 11,'note' => 'Sol #'];
$notes[117] = ['octave' => 11,'note' => 'La'];
$notes[118] = ['octave' => 11,'note' => 'La #'];
$notes[119] = ['octave' => 11,'note' => 'Si'];
$notes[120] = ['octave' => 11,'note' => 'Do'];
$notes[121] = ['octave' => 11,'note' => 'Do #'];
$notes[122] = ['octave' => 11,'note' => 'Re'];
$notes[123] = ['octave' => 11,'note' => 'Re #'];
$notes[124] = ['octave' => 11,'note' => 'Mi'];
$notes[125] = ['octave' => 11,'note' => 'Fa'];
$notes[126] = ['octave' => 11,'note' => 'Fa #'];
$notes[127] = ['octave' => 11,'note' => 'Sol'];
